server:
  port: 8090
  servlet:
    session:
      timeout: 1800s
spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
